name: possytem
description: "A POS System for managing food and drinks with RFID support"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.1
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  responsive_framework: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  uuid: ^4.4.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/